kind: ConfigMap
apiVersion: v1
metadata:
  name: search-service
  namespace: dev
data:
  application.yaml: |-

    server:
      port: 8090

    spring:
      application:
        name: search-service

      rabbitmq:
        addresses: rabbitmq
        username: guest
        password: guest

      datasource:
        url: jdbc:h2:mem:searchdb
        username: sa
        password:

      h2:
        console:
          enabled: true

      jpa:
        hibernate:
          ddl-auto: update

      logging:
        level:
          com:
            jdum:
              booking: DEBUG
