spec:
  template:
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
            scheme: HTTP